version: '3.1'

services:

  mongo:
    build: ./mongodb_rs
    restart: always
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: jagath
      MONGO_INITDB_ROOT_PASSWORD: jagath123
      MONGO_INITDB_DATABASE: mongo
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - nana_mongo_vol:/app/data/db:rw
      

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jagath
      ME_CONFIG_MONGODB_ADMINPASSWORD: jagath123
      ME_CONFIG_MONGODB_SERVER: mongo_container
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'

      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mongo-network

  user-app:
    image: user-app-image
    build: .
    ports:
      - 3000:3000
    networks:
      - mongo-network

networks:
  mongo-network:
    # driver:bridge

volumes:
  nana_mongo_vol:
